### ISSUE TITLE
Add person status while requesting assistance

### ISSUE THREAD

**Issue by astar26** [itay-sho/LevEchad#171]
Options:
1. Isolation
2. Sick
3. Elderly
4. Lonely
5. Normal

Remeber to update all relevant forms, tables and Excel output.

**Comment by stavlocker** [comment]
@astar26 
How are we going to ask people this? Like
סיבה לבקשת עזרה: בידוד/חולה מאומת/קבוצת סיכון/בדידות
sounds like people wouldn't want to fill out that they need assistance because they're lonely. How can we phrase it to sound better? Or what will the question/answers be? (For example "מבוגרים בקבוצת סיכון" could sound better than "זקנים")

**Comment by astar26** [comment]
It should be a choice between the states, and possibly make it optional, although it helps quite a lot when trying to understand if the request is legit.
@amirkasher opinion?

**Comment by stavlocker** [comment]
@astar26 I just think we need to think of how to word the options here.

 * Isolation == "בבידוד", this one is the easiest
 * Is "Sick" a confirmed COVID-19 patient or just someone who's sick in general?
 * Elderly can be "מבוגרים בקבוצת סיכון"
 * What is "Lonely"?
 * We can't have "Normal" as an option (implying the other options are not normal). Maybe something like "None of the above" or "Other" could work

Once we decide on these I can implement it - it should be a small addition.

**Comment by amirkasher** [comment]
As i see it, there are only 3 options:
1. solation == בבידוד, any one who diagnosed with COVID - 19 
2. Sick can be == קבוצת סיכון גבוהה, any one who is in high risk, can be anyone with background illness (can be also 30 year old woman with Asthma or Elderly = person who is above 60 years old) 
3. Other == אחר, with a text input as a description

**Comment by stavlocker** [comment]
@amirkasher Alright, cool. Then we don't want "sick" right? only "בבידוד", "קבוצת סיכון גבוהה", "אחר"

**Comment by amirkasher** [comment]
Perfect
the אחר doesn't need to be be with input..

**Comment by stavlocker** [comment]
We currently have the help request "סיוע לעובדים חיוניים" for essentials workers in need of help.

This sort of collides with the "request reason / person status", because the help request type is basically the request reason. Do we want:

 * To eliminate the "סיוע לעובדים חיוניים" help request and add a "עובד חיוני" status to the request reason?
 * To keep the "סיוע לעובדים חיוניים" help request and additionally add the "עובד חיוני" status to the request reason?
 * Keep everything like it is now

@amirkasher
